cache:
  directories:
    - ./_build/plt

services:
  - postgresql
  - mysql

addons:
  postgresql: "9.6"
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_script:
  - psql -c "CREATE DATABASE puremigration;" -U postgres
  - psql -c "CREATE USER puremigration WITH PASSWORD 'puremigration';" -U postgres

before_install:
  - mysql -e "CREATE DATABASE puremigration;"
  - mysql -e "CREATE USER 'puremigration@localhost' IDENTIFIED BY 'puremigration'";
  - mysql -e "GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP ON puremigration.* TO 'puremigration@localhost';"

language: erlang

otp_release:
  - 21.0

script:
  - make travis