cache:
  directories:
    - ./_build/plt

services:
  - postgresql
  - mysql

addons:
  postgresql: "9.6"
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_script:
  - psql -c "CREATE DATABASE migration;" -U postgres
  - psql -c "CREATE USER migration WITH PASSWORD 'migration';" -U postgres

language: erlang

otp_release:
  - 21.0

script:
  - make travis