{application,rebar3_lint,
             [{description,"A rebar plugin for elvis"},
              {vsn,"0.1.10"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[rebar3_lint,rebar3_lint_prv]},
              {maintainers,["Heinz N. Gies <heinz@licenser.net>"]},
              {licenses,["MIT"]},
              {links,[{"github",
                       "https://github.com/project-fifo/rebar3_lint"}]}]}.
