{application,zipper,
             [{description,"Generic Zipper Implementation for Erlang"},
              {vsn,"1.0.1"},
              {applications,[kernel,stdlib]},
              {modules,[zipper,zipper_default]},
              {registered,[]},
              {maintainers,["Inaka"]},
              {licenses,["Apache 2.0"]},
              {links,[{"Github","https://github.com/inaka/zipper"}]},
              {build_tools,["erlang.mk","rebar"]}]}.
